// Generated by ts-to-zod
import { z } from "zod";

export const envelopeTypeSchema = z.union([z.literal("task"), z.literal("ack"), z.literal("result"), z.literal("escalate"), z.literal("notify"), z.literal("summary"), z.literal("operator")]);

export const envelopeStateSchema = z.union([z.literal("pending"), z.literal("read"), z.literal("actioned"), z.literal("archived")]);

export const envelopeSchema = z.object({
    _type: z.literal("envelope"),
    id: z.string(),
    envelope_type: envelopeTypeSchema,
    from: z.string(),
    to: z.string(),
    subject: z.string(),
    at: z.string(),
    state: envelopeStateSchema,
    priority: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]).optional(),
    thread_id: z.string().optional(),
    reply_to: z.string().optional(),
    payload: z.record(z.string(), z.unknown()).optional(),
    requires_decision: z.boolean().optional(),
    decision_options: z.array(z.string()).optional(),
    ack_required: z.boolean().optional(),
    expires_at: z.string().optional()
});

export const durableTaskSchema = z.object({
    _type: z.literal("task"),
    id: z.string(),
    queue: z.string(),
    subject: z.string(),
    description: z.string().optional(),
    state: z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed"), z.literal("blocked"), z.literal("failed")]),
    created_at: z.string(),
    updated_at: z.string(),
    from: z.string().optional(),
    ke_fit_score: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]).optional(),
    owner: z.string().optional(),
    estimated_hours: z.number().optional(),
    due_date: z.string().optional(),
    jira_key: z.string().optional(),
    depends_on: z.array(z.string()).optional(),
    blocks: z.array(z.string()).optional(),
    evaluator: z.object({
        pass_if: z.array(z.string()),
        fail_if: z.array(z.string())
    }).optional(),
    payload: z.record(z.string(), z.unknown()).optional(),
    result: z.record(z.string(), z.unknown()).optional(),
    error: z.string().optional()
});

export const transitionEventSchema = z.union([z.literal("claim"), z.literal("complete"), z.literal("block"), z.literal("unblock"), z.literal("fail"), z.literal("retry"), z.literal("ack"), z.literal("read")]);

export const transitionSchema = z.object({
    _type: z.literal("transition"),
    id: z.string(),
    at: z.string(),
    event: transitionEventSchema.optional(),
    prior_state: z.string().optional(),
    new_state: z.string().optional(),
    owner: z.string().optional(),
    status: z.string().optional(),
    acked_by: z.string().optional(),
    read_by: z.string().optional(),
    note: z.string().optional(),
    error: z.string().optional()
});

export const mailboxRecordSchema = z.union([envelopeSchema, transitionSchema]);

export const queueRecordSchema = z.union([durableTaskSchema, transitionSchema]);

export const e2MRecordSchema = z.union([envelopeSchema, durableTaskSchema, transitionSchema]);

export const operatorEnvelopeSchema = envelopeSchema.extend({
    envelope_type: z.union([z.literal("operator"), z.literal("escalate"), z.literal("summary")]),
    to: z.literal("operator"),
    requires_decision: z.boolean()
});
