# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Evaluator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fail_if: list[str]
    pass_if: list[str]


class KeFitScore(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5


class State(StrEnum):
    pending = 'pending'
    in_progress = 'in_progress'
    completed = 'completed'
    blocked = 'blocked'
    failed = 'failed'


class DurableTask(BaseModel):
    """
    DurableTask — queued work items in cowork/data/queues/<domain>.jsonl Separate from Envelope: tasks are claimed by coworkers, envelopes are messages between them.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_type: Literal['task'] = Field(..., alias='_type')
    blocks: list[str] | None = None
    created_at: str
    depends_on: list[str] | None = None
    description: str | None = None
    due_date: str | None = None
    error: str | None = None
    estimated_hours: float | None = None
    evaluator: Evaluator | None = None
    from_: str | None = Field(None, alias='from')
    id: str
    jira_key: str | None = None
    ke_fit_score: KeFitScore | None = None
    owner: str | None = None
    payload: dict[str, Any] | None = None
    queue: str
    result: dict[str, Any] | None = None
    state: State
    subject: str
    updated_at: str


class Priority(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5


class EnvelopeState(StrEnum):
    pending = 'pending'
    read = 'read'
    actioned = 'actioned'
    archived = 'archived'


class EnvelopeType(StrEnum):
    """
    CANONICAL SCHEMA SOURCE for the e2m (envelope-to-mailbox) protocol.

    This file is the SINGLE SOURCE OF TRUTH. All other bindings are GENERATED, never hand-edited:   ts-to-zod              envelope.ts  → envelope.zod.ts     (runtime validation)   zod-to-json-schema     *.zod.ts     → envelope.schema.json (interlingua)   datamodel-code-gen     *.schema.json→ envelope.py          (Python · pydantic v2)   typify / quicktype     *.schema.json→ envelope.rs          (Rust · serde) Regenerate with: npm run schema:gen   (see cowork/schemas/E2M-PROTOCOL.md)

    Three record kinds live in the JSONL files, discriminated by `_type`:   "envelope"   — a message between coworkers (cowork/data/mailbox/<id>.jsonl)   "task"       — a DurableTask queue item   (cowork/data/queues/<domain>.jsonl)   "transition" — a state-change / ack row appended after an envelope or task

    Coworkers MUST emit these typed records, never raw JSON blobs. The `payload` field is the only open schema — everything else is typed.
    """

    task = 'task'
    ack = 'ack'
    result = 'result'
    escalate = 'escalate'
    notify = 'notify'
    summary = 'summary'
    operator = 'operator'


class TransitionEvent(StrEnum):
    claim = 'claim'
    complete = 'complete'
    block = 'block'
    unblock = 'unblock'
    fail = 'fail'
    retry = 'retry'
    ack = 'ack'
    read = 'read'


class Envelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_type: Literal['envelope'] = Field(..., alias='_type')
    ack_required: bool | None = None
    at: str
    decision_options: list[str] | None = None
    envelope_type: EnvelopeType
    expires_at: str | None = None
    from_: str = Field(..., alias='from')
    id: str
    payload: dict[str, Any] | None = None
    priority: Priority | None = None
    reply_to: str | None = None
    requires_decision: bool | None = None
    state: EnvelopeState
    subject: str
    thread_id: str | None = None
    to: str


class Transition(BaseModel):
    """
    Transition — an append-only state-change row for a task or envelope. The id matches the task/envelope it transitions; latest-line-wins on read.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_type: Literal['transition'] = Field(..., alias='_type')
    acked_by: str | None = None
    at: str
    error: str | None = None
    event: TransitionEvent | None = None
    id: str
    new_state: str | None = None
    note: str | None = None
    owner: str | None = None
    prior_state: str | None = None
    read_by: str | None = None
    status: str | None = None


class E2MRecord(RootModel[Envelope | DurableTask | Transition]):
    root: Envelope | DurableTask | Transition = Field(
        ..., description='Any e2m record.'
    )


class Model(RootModel[E2MRecord]):
    root: E2MRecord
