-- Kimball DW schema for the model registry.
-- Generated by kimball-model-yaml-skill v0.1.0 (2026-06-09).
-- @cite data/models/kimball_ddl.sql

BEGIN;

CREATE SCHEMA IF NOT EXISTS dw;

-- ---------------------------------------------------------------------------
-- dim_date — SCD Type 0 (immutable calendar)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_date (
    date_key        INTEGER  PRIMARY KEY,
    full_date       DATE     NOT NULL UNIQUE,
    year            SMALLINT NOT NULL,
    quarter         SMALLINT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month           SMALLINT NOT NULL CHECK (month   BETWEEN 1 AND 12),
    week_iso        SMALLINT NOT NULL CHECK (week_iso BETWEEN 1 AND 53),
    day_of_week     SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    is_weekend      BOOLEAN  NOT NULL
);

INSERT INTO dw.dim_date VALUES (20260609,'2026-06-09',2026,2,6,24,2,FALSE)
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- dim_model — SCD Type II
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_model (
    surrogate_key       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_model_id        TEXT           NOT NULL,
    row_effective_from  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    row_effective_to    TIMESTAMPTZ    NOT NULL DEFAULT 'infinity',
    is_current          BOOLEAN        NOT NULL DEFAULT TRUE,
    display_name        TEXT           NOT NULL,
    family              TEXT           NOT NULL,
    tier                TEXT           NOT NULL
                            CHECK (tier IN ('flagship','mid','haiku','preview','limited','deprecated')),
    context_window_k    INTEGER        NOT NULL,
    max_output_k        INTEGER        NOT NULL,
    price_input_mtok    NUMERIC(18,6)  NOT NULL,
    price_output_mtok   NUMERIC(18,6)  NOT NULL,
    thinking_mode       TEXT,
    safety_classifiers  BOOLEAN        NOT NULL DEFAULT TRUE,
    glasswing_only      BOOLEAN        NOT NULL DEFAULT FALSE,
    successor_to        TEXT,
    data_retention_days INTEGER,
    zero_data_retention BOOLEAN        NOT NULL DEFAULT FALSE,
    -- BM25 search vector (updated by trigger)
    tsv                 TSVECTOR GENERATED ALWAYS AS (
                            to_tsvector('english',
                                coalesce(display_name,'') || ' ' ||
                                coalesce(family,'') || ' ' ||
                                coalesce(api_model_id,''))
                        ) STORED,
    source_system       TEXT           NOT NULL DEFAULT 'model-registry',
    loaded_at           TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    UNIQUE (api_model_id, row_effective_from)
);

CREATE INDEX IF NOT EXISTS idx_dim_model_current ON dw.dim_model (api_model_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_dim_model_tsv     ON dw.dim_model USING GIN (tsv);

-- ---------------------------------------------------------------------------
-- dim_model_platform — SCD Type I
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_model_platform (
    surrogate_key   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_model_id    TEXT    NOT NULL,
    platform        TEXT    NOT NULL,
    available       BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (api_model_id, platform)
);
CREATE INDEX IF NOT EXISTS idx_dim_model_platform_model ON dw.dim_model_platform (api_model_id);

-- ---------------------------------------------------------------------------
-- dim_model_feature — SCD Type I
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_model_feature (
    surrogate_key   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_model_id    TEXT    NOT NULL,
    feature         TEXT    NOT NULL,
    beta            BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (api_model_id, feature)
);
CREATE INDEX IF NOT EXISTS idx_dim_model_feature_model ON dw.dim_model_feature (api_model_id);

-- ---------------------------------------------------------------------------
-- dim_model_access — SCD Type III
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_model_access (
    surrogate_key           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_model_id            TEXT NOT NULL UNIQUE,
    current_access_tier     TEXT NOT NULL
                                CHECK (current_access_tier IN ('ga','glasswing','deprecated')),
    prior_access_tier       TEXT
                                CHECK (prior_access_tier IN ('ga','glasswing','deprecated') OR prior_access_tier IS NULL),
    access_tier_changed_at  TIMESTAMPTZ,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- fact_model_pricing — periodic snapshot
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.fact_model_pricing (
    surrogate_key       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date_key            INTEGER        NOT NULL REFERENCES dw.dim_date(date_key),
    model_sk            BIGINT         NOT NULL REFERENCES dw.dim_model(surrogate_key),
    price_input_mtok    NUMERIC(18,6)  NOT NULL,
    price_output_mtok   NUMERIC(18,6)  NOT NULL,
    context_window_k    INTEGER        NOT NULL,
    snapshot_at         TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    UNIQUE (date_key, model_sk)
);
CREATE INDEX IF NOT EXISTS idx_fact_pricing_date  ON dw.fact_model_pricing (date_key);
CREATE INDEX IF NOT EXISTS idx_fact_pricing_model ON dw.fact_model_pricing (model_sk);

-- ---------------------------------------------------------------------------
-- fact_model_usage — transactional fact stub
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.fact_model_usage (
    surrogate_key       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date_key            INTEGER  NOT NULL REFERENCES dw.dim_date(date_key),
    model_sk            BIGINT   NOT NULL REFERENCES dw.dim_model(surrogate_key),
    platform            TEXT     NOT NULL,
    input_tokens        BIGINT   NOT NULL DEFAULT 0,
    output_tokens       BIGINT   NOT NULL DEFAULT 0,
    cache_read_tokens   BIGINT   NOT NULL DEFAULT 0,
    refusal_count       INTEGER  NOT NULL DEFAULT 0,
    fallback_count      INTEGER  NOT NULL DEFAULT 0,
    loaded_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fact_usage_date_model ON dw.fact_model_usage (date_key, model_sk);

-- ---------------------------------------------------------------------------
-- events_model — append-only lifecycle audit
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.events_model (
    event_id        BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_key        INTEGER     NOT NULL REFERENCES dw.dim_date(date_key),
    api_model_id    TEXT        NOT NULL,
    event_type      TEXT        NOT NULL
                        CHECK (event_type IN (
                            'model_announced','model_ga','model_deprecated',
                            'pricing_changed','feature_added','feature_removed',
                            'platform_added','platform_removed',
                            'access_tier_changed','successor_linked'
                        )),
    actor           TEXT,
    old_value       JSONB,
    new_value       JSONB,
    source_url      TEXT,
    notes           TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_model_id_time   ON dw.events_model (api_model_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_model_type_time ON dw.events_model (event_type, occurred_at DESC);

COMMIT;
