// Generated by ts-to-zod
import { z } from "zod";

// Clean interface file for ts-to-zod — no zod imports, pure TypeScript
export const envelopeIdSchema = z.string();

export const mailboxProtocolSchema = z.union([z.literal("e2m"), z.literal("mcp"), z.literal("a2a"), z.literal("acp")]);

export const mailboxAddressSchema = z.object({
    protocol: mailboxProtocolSchema,
    host: z.string(),
    name: z.string(),
    version: z.string().optional()
});

export const envelopeStatusSchema = z.union([z.literal("pending"), z.literal("delivered"), z.literal("processing"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("expired")]);

export const payloadKindSchema = z.union([z.literal("task"), z.literal("oauth"), z.literal("event"), z.literal("query"), z.literal("reply"), z.literal("error")]);

export const envelopeHeaderSchema = z.object({
    envelopeId: envelopeIdSchema,
    protocol: z.literal("io.e2m/envelope"),
    version: z.literal("draft"),
    sentAt: z.string(),
    from: mailboxAddressSchema,
    to: mailboxAddressSchema,
    replyTo: mailboxAddressSchema.optional(),
    correlationId: envelopeIdSchema.optional(),
    payloadKind: payloadKindSchema,
    ttlMs: z.number().optional().nullable(),
    traceId: z.string().optional()
});

export const envelopeErrorSchema = z.object({
    code: z.number(),
    message: z.string(),
    data: z.record(z.string(), z.unknown()).optional().nullable()
});

export const envelopeSchema = z.object({
    header: envelopeHeaderSchema,
    status: envelopeStatusSchema,
    payload: z.record(z.string(), z.unknown()),
    error: envelopeErrorSchema.optional().nullable(),
    meta: z.record(z.string(), z.unknown()).optional()
});

// Task payload interfaces
export const taskStatusSchema = z.union([z.literal("pending"), z.literal("working"), z.literal("input_required"), z.literal("delegated"), z.literal("completed"), z.literal("failed"), z.literal("cancelled")]);

export const taskPrioritySchema = z.union([z.literal("low"), z.literal("normal"), z.literal("high"), z.literal("critical")]);

export const anthropicModelTargetSchema = z.object({
    provider: z.literal("anthropic"),
    model: z.string(),
    maxTokens: z.number().optional(),
    systemPrompt: z.string().optional()
});

export const externalAgentTargetSchema = z.object({
    protocol: z.union([z.literal("mcp"), z.literal("a2a"), z.literal("acp"), z.literal("e2m")]),
    address: z.string()
});

export const taskTargetSchema = z.union([anthropicModelTargetSchema, externalAgentTargetSchema]);

export const taskSchema = z.object({
    taskId: z.string(),
    status: taskStatusSchema,
    priority: taskPrioritySchema.optional(),
    statusMessage: z.string().optional().nullable(),
    createdAt: z.string(),
    lastUpdatedAt: z.string(),
    ttlMs: z.number().optional().nullable(),
    pollIntervalMs: z.number().optional(),
    target: taskTargetSchema.optional(),
    parentTaskId: z.string().optional().nullable(),
    delegatedTo: z.string().optional().nullable()
});

// Memory store interfaces (for ts-to-zod)
export const memoryAccessSchema = z.union([z.literal("read_write"), z.literal("read_only")]);

export const memoryOperationSchema = z.union([z.literal("create"), z.literal("update"), z.literal("delete"), z.literal("redact")]);

export const memoryStoreStatusSchema = z.union([z.literal("active"), z.literal("archived")]);

export const memoryStoreSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    status: memoryStoreStatusSchema,
    archived_at: z.string().nullable(),
    created_at: z.string(),
    updated_at: z.string()
});

export const memorySchema = z.object({
    id: z.string(),
    memory_store_id: z.string(),
    path: z.string(),
    content: z.string().optional().nullable(),
    content_sha256: z.string(),
    created_at: z.string(),
    updated_at: z.string()
});

export const contentSha256PreconditionSchema = z.object({
    type: z.literal("content_sha256"),
    content_sha256: z.string()
});

export const memoryStoreResourceSchema = z.object({
    type: z.literal("memory_store"),
    memory_store_id: z.string(),
    access: memoryAccessSchema,
    instructions: z.string().optional()
});

export const createMemoryParamsSchema = z.object({
    path: z.string(),
    content: z.string().optional()
});

export const updateMemoryParamsSchema = z.object({
    path: z.string().optional(),
    content: z.string().optional(),
    precondition: contentSha256PreconditionSchema.optional()
});
