-- dim_agent_templates_cowork.sql
-- Seed: 11 cowork/ template rows for dw.dim_agent_templates
-- @cite data/models/alloydb/dim_agent_templates.yaml
-- @cite cowork/agents/manifest.json
-- @cite cowork/agents/tests/contracts.ts (DataSeedResult)
-- Generated by: data-agent | task a1b2c3d4-0006-4000-8000-000000000006

INSERT INTO dw.dim_agent_templates
  (source_org, slug, install_status, file_path, domain, ke_fit_score, created_at)
VALUES
  ('cowork', 'analytics', 'available', 'cowork/artifacts/templates/analytics.html', 'data',               5, NOW()),
  ('cowork', 'plan',      'available', 'cowork/artifacts/templates/plan.html',      'product-management', 5, NOW()),
  ('cowork', 'brain',     'available', 'cowork/artifacts/templates/brain.html',     'data',               5, NOW()),
  ('cowork', 'dispatch',  'available', 'cowork/artifacts/templates/dispatch.html',  'product-management', 5, NOW()),
  ('cowork', 'calendar',  'available', 'cowork/artifacts/templates/calendar.html',  'product-management', 4, NOW()),
  ('cowork', 'content',   'available', 'cowork/artifacts/templates/content.html',   'engineering',        4, NOW()),
  ('cowork', 'slides',    'available', 'cowork/artifacts/templates/slides.html',    'design',             3, NOW()),
  ('cowork', 'mail',      'available', 'cowork/artifacts/templates/mail.html',      'sales',              4, NOW()),
  ('cowork', 'forms',     'available', 'cowork/artifacts/templates/forms.html',     'product-management', 4, NOW()),
  ('cowork', 'clips',     'available', 'cowork/artifacts/templates/clips.html',     'data',               3, NOW()),
  ('cowork', 'design',    'available', 'cowork/artifacts/templates/design.html',    'design',             4, NOW())
;

-- Verification:
-- SELECT COUNT(*) FROM dw.dim_agent_templates WHERE source_org = 'cowork';
-- Expected: 11
