// scripts/schema-gen-py-rs.ts
//
// Second stage of `npm run schema:gen`: projects cowork/schemas/envelope.schema.json
// (already regenerated by ts-to-zod + ts-json-schema-generator) into the Python and
// Rust language bindings.
//
//   datamodel-code-generator  envelope.schema.json → envelope.py  (pydantic v2)
//   quicktype                 envelope.schema.json → envelope.rs (serde)
//
// Both invocations pin flags for deterministic output (required by
// `npm run verify:schema`'s git-diff drift check):
//   - datamodel-codegen: --disable-timestamp (its default embeds a generation
//     timestamp in the file header, which would fail the drift check every run)
//   - quicktype: has no timestamp/nondeterminism in its Rust output; verified
//     byte-identical across repeated runs (see cowork/schemas/E2M-PROTOCOL.md)
//
// quicktype's Rust target has no serde(tag = "_type") internally-tagged-enum
// support — it flattens the Envelope | DurableTask | Transition union into one
// struct with every field Option<...>. A static TODO header is prepended to
// envelope.rs flagging this; see that file for the full explanation.
//
// @cite cowork/schemas/E2M-PROTOCOL.md
// @cite cowork/schemas/envelope.schema.json

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SCHEMAS_DIR = resolve(REPO_ROOT, "cowork", "schemas");

const SCHEMA_JSON = resolve(SCHEMAS_DIR, "envelope.schema.json");
const ENVELOPE_PY = resolve(SCHEMAS_DIR, "envelope.py");
const ENVELOPE_RS = resolve(SCHEMAS_DIR, "envelope.rs");

const RS_TODO_HEADER = `// TODO: verify serde tagging matches envelope.ts precisely, quicktype output may need manual correction
//
// quicktype's Rust target has no internally-tagged-enum / serde(tag = "_type")
// support: it flattens Envelope | DurableTask | Transition into ONE struct
// (E2MRecord) with every field Option<...> except `+ "`id`" + ` and the `+ "`Type`" + ` enum,
// instead of a proper tagged union. This compiles (verified via a scratch
// cargo build) but does not enforce the same shape guarantees as
// envelope.ts/envelope.zod.ts — e.g. nothing stops constructing an E2MRecord
// with envelope_type set but queue also set. Regenerated from
// envelope.schema.json via:
//   quicktype --src-lang schema --src envelope.schema.json --lang rust \\
//     --top-level E2MRecord --visibility public --derive-debug --derive-clone
// Candidates for a follow-up: typify (better serde-tag support) or hand-written
// #[serde(tag = "_type")] enum wrapping three structs generated separately.
//
`;

function generatePython(): void {
  execFileSync(
    "python3",
    [
      "-m", "datamodel_code_generator",
      "--input", SCHEMA_JSON,
      "--input-file-type", "jsonschema",
      "--output", ENVELOPE_PY,
      "--output-model-type", "pydantic_v2.BaseModel",
      "--disable-timestamp",
      "--use-schema-description",
      "--target-python-version", "3.11",
      "--field-constraints",
      "--use-standard-collections",
    ],
    { cwd: REPO_ROOT, stdio: "inherit" },
  );
}

function generateRust(): void {
  const quicktypeBin = resolve(REPO_ROOT, "node_modules", ".bin", "quicktype");
  execFileSync(
    quicktypeBin,
    [
      "--src-lang", "schema",
      "--src", SCHEMA_JSON,
      "--lang", "rust",
      "--top-level", "E2MRecord",
      "--visibility", "public",
      "--derive-debug",
      "--derive-clone",
      "--out", ENVELOPE_RS,
    ],
    { cwd: REPO_ROOT, stdio: "inherit" },
  );
  const body = readFileSync(ENVELOPE_RS, "utf8");
  writeFileSync(ENVELOPE_RS, RS_TODO_HEADER + body, "utf8");
}

generatePython();
generateRust();
console.log("envelope.py + envelope.rs generated.");
