#!/usr/bin/env bash
# setup-chat.sh — Bootstrap e2m project memory stores for Claude.ai / Cowork sessions
#
# AUTH MODEL: Egress proxy — no API key needed.
# Run inside a Claude Artifact, Claude Code session, or Cowork task.
# The egress proxy at 160.79.104.10 (Egress Gateway SDS CA) injects auth from session.
#
# Usage: ./setup-chat.sh [--dry-run]
set -euo pipefail

DRY_RUN=false
for arg in "$@"; do case $arg in --dry-run) DRY_RUN=true ;; esac done

log()  { echo "[setup-chat] $*"; }
ok()   { echo "[setup-chat] ✓ $*"; }
err()  { echo "[setup-chat] ✗ $*" >&2; exit 1; }

RESOURCE_IDS_FILE="$(dirname "$0")/../project-rag/resource-ids.yaml"

# No x-api-key — auth injected by egress proxy when inside session context
api() {
  local method="$1" path="$2"; shift 2
  $DRY_RUN && { log "DRY: $method $path"; echo '{"id":"memstore_DRY"}'; return; }
  curl -sf -X "$method" "https://api.anthropic.com$path" \
    -H "anthropic-version: 2023-06-01" \
    -H "anthropic-beta: managed-agents-2026-04-01" \
    -H "content-type: application/json" "$@"
}

# ── Create project-context store (read_write per session) ─────────────────────
log "Creating project-context memory store..."
CTX_STORE=$(api POST /v1/memory_stores -d '{
  "name": "e2m-project-context",
  "description": "Per-session context for e2m-workspaces: task state, decisions, conventions. Check before starting any task."
}')
CTX_ID=$(echo "$CTX_STORE" | jq -r '.id')
ok "project-context: $CTX_ID"

# Seed with CLAUDE.md
CLAUDE_MD=$(cat "$(dirname "$0")/../CLAUDE.md" 2>/dev/null || echo "# e2m-workspaces")
api POST "/v1/memory_stores/$CTX_ID/memories" \
  -d "$(jq -n --arg c "$CLAUDE_MD" '{"path":"/project/CLAUDE.md","content":$c}')" >/dev/null
ok "Seeded /project/CLAUDE.md"

# Seed with egress proxy auth reference
api POST "/v1/memory_stores/$CTX_ID/memories" -d '{
  "path": "/project/auth-model.md",
  "content": "# Auth Model\nNo ANTHROPIC_API_KEY. Egress proxy at 160.79.104.10 (Egress Gateway SDS CA) injects auth from session.\nCode: fetch() with no key header — works in Artifact/Claude Code/Cowork.\nbash_tool raw shell: returns 401.\nWorker environments use ANTHROPIC_ENVIRONMENT_KEY (separate from API key)."
}' >/dev/null
ok "Seeded /project/auth-model.md"

# ── Create shared-reference store (read_only for sessions) ────────────────────
log "Creating shared-reference memory store..."
REF_STORE=$(api POST /v1/memory_stores -d '{
  "name": "e2m-shared-reference",
  "description": "Read-only reference: e2m protocol specs, MCP ext schemas, API conventions. Do not write here."
}')
REF_ID=$(echo "$REF_STORE" | jq -r '.id')
ok "shared-reference: $REF_ID"

api POST "/v1/memory_stores/$REF_ID/memories" -d '{
  "path": "/e2m/envelope-summary.md",
  "content": "# E2M Envelope\nprotocol: io.e2m/envelope\nPayloadKinds: task, oauth, event, query, reply, error\nMailbox: {protocol}:{host}/{name}\nAll timestamps: ISO 8601. All IDs: UUIDv7.\nBeta header: managed-agents-2026-04-01"
}' >/dev/null
ok "Seeded /e2m/envelope-summary.md"

api POST "/v1/memory_stores/$REF_ID/memories" -d '{
  "path": "/managed-agents/limits.md",
  "content": "# Memory Limits\n100kB/memory, 2000 memories/store, 8 stores/session\nRate: 300 create/min, 600 read/min per org\nVersions: 30-day retention (recent always kept)\narchive is one-way"
}' >/dev/null
ok "Seeded /managed-agents/limits.md"

# ── Write resource-ids.yaml ───────────────────────────────────────────────────
mkdir -p "$(dirname "$RESOURCE_IDS_FILE")"
cat > "$RESOURCE_IDS_FILE" << YAML
# resource-ids.yaml — generated by setup-chat.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Auth: egress proxy session context — no API key stored here
memory_stores:
  project_context:  $CTX_ID
  shared_reference: $REF_ID
agents:
  coordinator:      "# fill after setup-code.sh"
environments:
  default:          "# fill after setup-linux/macos/winget.sh"
  environment_key:  "# envkey_... — worker auth only, keep secure"
YAML
ok "Wrote $RESOURCE_IDS_FILE"

echo ""
ok "setup-chat.sh complete"
log "project_context:  $CTX_ID  (attach: access: read_write)"
log "shared_reference: $REF_ID  (attach: access: read_only)"
echo "   Next: ./setup-code.sh to install ant CLI + create coordinator agent"
