// Generated by ts-to-zod
import { z } from "zod";

import { z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z, z } from "zod";

export const memoryStoreIdSchema = z.literal(z.infer);

export const memoryIdSchema = z.literal(z.infer);

export const memoryVersionIdSchema = z.literal(z.infer);

export const memoryAccessSchema = z.literal(z.infer);

export const memoryOperationSchema = z.literal(z.infer);

export const memoryStoreStatusSchema = z.literal(z.infer);

export const memoryItemTypeSchema = z.literal(z.infer);

export const memoryStoreSchema = z.literal(z.infer);

export const createMemoryStoreParamsSchema = z.literal(z.infer);

export const updateMemoryStoreParamsSchema = z.literal(z.infer);

export const listMemoryStoresParamsSchema = z.literal(z.infer);

export const memorySchema = z.literal(z.infer);

export const memoryListItemSchema = z.literal(z.infer);

export const contentSha256PreconditionSchema = z.literal(z.infer);

export const createMemoryParamsSchema = z.literal(z.infer);

export const updateMemoryParamsSchema = z.literal(z.infer);

export const listMemoriesParamsSchema = z.literal(z.infer);

export const memoryVersionSchema = z.literal(z.infer);

export const listMemoryVersionsParamsSchema = z.literal(z.infer);

export const memoryStoreResourceSchema = z.literal(z.infer);

export const memoryStoreListSchema = z.literal(z.infer);

export const memoryListSchema = z.literal(z.infer);

export const memoryVersionListSchema = z.literal(z.infer);

export const apiHeadersSchema = z.object({
    "x-api-key": z.string(),
    "anthropic-version": z.any(),
    "anthropic-beta": z.any(),
    "content-type": z.literal("application/json")
});
